### ISSUE TITLE
ProtectTable returning insuppressible messages

### ISSUE THREAD

**Issue by Anders725** [statisticsnorway/easySdcTable#12]
Hello,

I would like to use ProtectTable from easySdcTable to suppress tables in an RMarkdown report.  Unfortunately, ProtectTable returns insuppressible messages that are output to my RMarkdown report and are unsightly (..... GaussSuppression_anySum: ..............................). How do I disable this?

Note: this could be fixed by separating the generation of the protected table and the printing of the protected table into separate chunks and using "include = FALSE" on the generation chunk. But, for the purposes of my project please assume this is not possible. The code for each table will be saved in an external R file that is loaded to the chunk, to make it easier to manage a large number of table files. I need a different method of suppressing the messages.

Below is example code with a reproducible example. I have included the "default" and two ways of trying to use R functions to suppress the messages.

Thanks.

---
title: "easySdcTable test"
---

```{r, echo = FALSE, warning = FALSE, message=FALSE}
library(easySdcTable)
library(kableExtra)

z2 <- EasyData("z2")


z2_protected <- ProtectTable( z2, 
                              dimVar = c("region", "hovedint", "kostragr"), 
                              freqVar = "ant", 
                              maxN = 5, 
                              protectZeros = FALSE, 
                              method = "Gauss",
                              suppression = "S" )
print(z2_protected$data)

z2_protected <- suppressMessages({suppressWarnings({ ProtectTable( z2, 
                            dimVar = c("region", "hovedint", "kostragr"), 
                            freqVar = "ant", 
                            maxN = 5, 
                            protectZeros = FALSE, 
                            method = "Gauss",
                            suppression = "S" ) }) })
print(z2_protected$data)

suppressMessages({suppressWarnings({ 
     z2_protected <- ProtectTable( z2, 
                            dimVar = c("region", "hovedint", "kostragr"), 
                            freqVar = "ant", 
                            maxN = 5, 
                            protectZeros = FALSE, 
                            method = "Gauss",
                            suppression = "S" ) 
     }) })

print(z2_protected$data)

```

**Comment by olangsrud** [comment]
To disable console printing, use both `IncProgress = NULL` and `printInc = FALSE`. Unfortunately, it is not easy to find this out from the documentation. I will try to improve it in the next version. `IncProgress` is the parameter used by easySdcTable, while `printInc` is a parameter for the underlying function, `GaussSuppression`.
```
z2_protected <- ProtectTable(z2, 
                             dimVar = c("region", "hovedint", "kostragr"), 
                             freqVar = "ant", 
                             maxN = 5, 
                             protectZeros = FALSE, 
                             method = "Gauss",
                             suppression = "S",
                             IncProgress = NULL, 
                             printInc = FALSE)
```
Note: I recommend using the `SuppressSmallCounts` function from the GaussSuppression package as an alternative to `ProtectTable`. It will yield the same results in this example. In addition, there are [many more possibilities with the use of `SuppressSmallCounts`](https://cran.r-project.org/web/packages/GaussSuppression/vignettes/Small_count_frequency_table_suppression.html) and other functions in the [GaussSuppression package](https://cran.r-project.org/package=GaussSuppression).

**Comment by Anders725** [comment]
Thank you very much for your quick response. I have tried out the GaussSuppression package you suggested (specifically the SuppressSmallCounts function) and it is working exactly as I need. I really appreciated your insight on how to disable console printing.
